<?php

namespace Database\Seeders;

use App\Models\Province;
use Illuminate\Database\Seeder;

class ProvincesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provinces = [
            ['id' => 1, 'name' => 'Agrigento'],
            ['id' => 2, 'name' => 'Alessandria'],
            ['id' => 3, 'name' => 'Ancona'],
            ['id' => 4, 'name' => 'Aosta'],
            ['id' => 5, 'name' => 'Arezzo'],
            ['id' => 6, 'name' => 'Ascoli-Piceno'],
            ['id' => 7, 'name' => 'Asti'],
            ['id' => 8, 'name' => 'Avellino'],
            ['id' => 9, 'name' => 'Bari'],
            ['id' => 10, 'name' => 'Barletta-Andria-Trani'],
            ['id' => 11, 'name' => 'Belluno'],
            ['id' => 12, 'name' => 'Benevento'],
            ['id' => 13, 'name' => 'Bergamo'],
            ['id' => 14, 'name' => 'Biella'],
            ['id' => 15, 'name' => 'Bologna'],
            ['id' => 16, 'name' => 'Bolzano'],
            ['id' => 17, 'name' => 'Brescia'],
            ['id' => 18, 'name' => 'Brindisi'],
            ['id' => 19, 'name' => 'Cagliari'],
            ['id' => 20, 'name' => 'Caltanissetta'],
            ['id' => 21, 'name' => 'Campobasso'],
            ['id' => 22, 'name' => 'Carbonia Iglesias'],
            ['id' => 23, 'name' => 'Caserta'],
            ['id' => 24, 'name' => 'Catania'],
            ['id' => 25, 'name' => 'Catanzaro'],
            ['id' => 26, 'name' => 'Chieti'],
            ['id' => 27, 'name' => 'Como'],
            ['id' => 28, 'name' => 'Cosenza'],
            ['id' => 29, 'name' => 'Cremona'],
            ['id' => 30, 'name' => 'Crotone'],
            ['id' => 31, 'name' => 'Cuneo'],
            ['id' => 32, 'name' => 'Enna'],
            ['id' => 33, 'name' => 'Fermo'],
            ['id' => 34, 'name' => 'Ferrara'],
            ['id' => 35, 'name' => 'Firenze'],
            ['id' => 36, 'name' => 'Foggia'],
            ['id' => 37, 'name' => 'Forli-Cesena'],
            ['id' => 38, 'name' => 'Frosinone'],
            ['id' => 39, 'name' => 'Genova'],
            ['id' => 40, 'name' => 'Gorizia'],
            ['id' => 41, 'name' => 'Grosseto'],
            ['id' => 42, 'name' => 'Imperia'],
            ['id' => 43, 'name' => 'Isernia'],
            ['id' => 44, 'name' => 'L\'Aquila'],
            ['id' => 45, 'name' => 'La-Spezia'],
            ['id' => 46, 'name' => 'Latina'],
            ['id' => 47, 'name' => 'Lecce'],
            ['id' => 48, 'name' => 'Lecco'],
            ['id' => 49, 'name' => 'Livorno'],
            ['id' => 50, 'name' => 'Lodi'],
            ['id' => 51, 'name' => 'Lucca'],
            ['id' => 52, 'name' => 'Macerata'],
            ['id' => 53, 'name' => 'Mantova'],
            ['id' => 54, 'name' => 'Massa-Carrara'],
            ['id' => 55, 'name' => 'Matera'],
            ['id' => 56, 'name' => 'Medio Campidano'],
            ['id' => 57, 'name' => 'Messina'],
            ['id' => 58, 'name' => 'Milano'],
            ['id' => 59, 'name' => 'Modena'],
            ['id' => 60, 'name' => 'Monza-Brianza'],
            ['id' => 61, 'name' => 'Napoli'],
            ['id' => 62, 'name' => 'Novara'],
            ['id' => 63, 'name' => 'Nuoro'],
            ['id' => 64, 'name' => 'Ogliastra'],
            ['id' => 65, 'name' => 'Olbia Tempio'],
            ['id' => 66, 'name' => 'Oristano'],
            ['id' => 67, 'name' => 'Padova'],
            ['id' => 68, 'name' => 'Palermo'],
            ['id' => 69, 'name' => 'Parma'],
            ['id' => 70, 'name' => 'Pavia'],
            ['id' => 71, 'name' => 'Perugia'],
            ['id' => 72, 'name' => 'Pesaro-Urbino'],
            ['id' => 73, 'name' => 'Pescara'],
            ['id' => 74, 'name' => 'Piacenza'],
            ['id' => 75, 'name' => 'Pisa'],
            ['id' => 76, 'name' => 'Pistoia'],
            ['id' => 77, 'name' => 'Pordenone'],
            ['id' => 78, 'name' => 'Potenza'],
            ['id' => 79, 'name' => 'Prato'],
            ['id' => 80, 'name' => 'Ragusa'],
            ['id' => 81, 'name' => 'Ravenna'],
            ['id' => 82, 'name' => 'Reggio-Calabria'],
            ['id' => 83, 'name' => 'Reggio-Emilia'],
            ['id' => 84, 'name' => 'Rieti'],
            ['id' => 85, 'name' => 'Rimini'],
            ['id' => 86, 'name' => 'Roma'],
            ['id' => 87, 'name' => 'Rovigo'],
            ['id' => 88, 'name' => 'Salerno'],
            ['id' => 89, 'name' => 'Sassari'],
            ['id' => 90, 'name' => 'Savona'],
            ['id' => 91, 'name' => 'Siena'],
            ['id' => 92, 'name' => 'Siracusa'],
            ['id' => 93, 'name' => 'Sondrio'],
            ['id' => 94, 'name' => 'Taranto'],
            ['id' => 95, 'name' => 'Teramo'],
            ['id' => 96, 'name' => 'Terni'],
            ['id' => 97, 'name' => 'Torino'],
            ['id' => 98, 'name' => 'Trapani'],
            ['id' => 99, 'name' => 'Trento'],
            ['id' => 100, 'name' => 'Treviso'],
            ['id' => 101, 'name' => 'Trieste'],
            ['id' => 102, 'name' => 'Udine'],
            ['id' => 103, 'name' => 'Varese'],
            ['id' => 104, 'name' => 'Venezia'],
            ['id' => 105, 'name' => 'Verbania'],
            ['id' => 106, 'name' => 'Vercelli'],
            ['id' => 107, 'name' => 'Verona'],
            ['id' => 108, 'name' => 'Vibo-Valentia'],
            ['id' => 109, 'name' => 'Vicenza'],
            ['id' => 110, 'name' => 'Viterbo'],
        ];

        foreach ($provinces as $province) {
            Province::updateOrInsert(
                ['id' => $province['id']],
                ['name' => $province['name']]
            );
        }
    }
}
